<a href="https://colab.research.google.com/github/Ena-AlexBrush/Fine-Tuning-Experiments/blob/main/GRPO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install datasets evaluate transformers[sentencepiece]

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (5.0.1)
Requirement already satisfied: evaluate in /usr/local/lib/python3.12/dist-packages (0.4.6)
Requirement already satisfied: transformers[sentencepiece] in /usr/local/lib/python3.12/dist-packages (5.13.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (0.8.0)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (0.2.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (5.29.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers[sentencepiece]) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers[sentencepiece]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers[sentencepiece]) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers[sentencepiece]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers[sentencepiece]) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers[sentencepiece]) (0.1.2)

In [ ]:
!pip install --upgrade torchao

Requirement already satisfied: torchao in /usr/local/lib/python3.12/dist-packages (0.17.0)

In [ ]:
!pip install trl[GRPOTrainer]

Requirement already satisfied: trl[GRPOTrainer] in /usr/local/lib/python3.12/dist-packages (1.9.2)
WARNING: trl 1.9.2 does not provide the extra 'grpotrainer'
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl[GRPOTrainer]) (1.14.0)
Requirement already satisfied: datasets>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from trl[GRPOTrainer]) (5.0.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl[GRPOTrainer]) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl[GRPOTrainer]) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl[GRPOTrainer]) (5.13.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (1.23.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (3.29.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (0.70.16)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (2025.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl[GRPOTrainer]) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl[GRPOTrainer]) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl[GRPOTrainer]) (0.26.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl[GRPOTrainer]) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl[GRPOTrainer]) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl[GRPOTrainer]) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl[GRPOTrainer]) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl[GRPOTrainer]) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl[GRPOTrainer]) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl[GRPOTrainer]) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl[GRPOTrainer]) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl[GRPOTrainer]) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl[GRPOTrainer]) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl[GRPOTrainer]) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.90)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl[GRPOTrainer]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl[GRPOTrainer]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl[GRPOTrainer]) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl[GRPOTrainer]) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl[GRPOTrainer]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl[GRPOTrainer]) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl[GRPOTrainer]) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl[GRPOTrainer]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl[GRPOTrainer]) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.56.2->trl[GRPOTrainer]) (0.1.2)

In [ ]:
!pip install trl[vllm]

Requirement already satisfied: trl[vllm] in /usr/local/lib/python3.12/dist-packages (1.9.2)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl[vllm]) (1.14.0)
Requirement already satisfied: datasets>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from trl[vllm]) (5.0.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl[vllm]) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl[vllm]) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl[vllm]) (5.13.1)
Collecting vllm<=0.25.1,>=0.17.0 (from trl[vllm])
  Using cached vllm-0.25.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: fastapi in /usr/local/lib/python3.12/dist-packages (from trl[vllm]) (0.136.3)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from trl[vllm]) (2.13.4)
Requirement already satisfied: aiohttp>=3.13.3 in /usr/local/lib/python3.12/dist-packages (from trl[vllm]) (3.14.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from trl[vllm]) (2.32.4)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.12/dist-packages (from trl[vllm]) (0.51.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[vllm]) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[vllm]) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[vllm]) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[vllm]) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[vllm]) (1.23.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[vllm]) (0.8.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->trl[vllm]) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->trl[vllm]) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->trl[vllm]) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->trl[vllm]) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->trl[vllm]) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->trl[vllm]) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->trl[vllm]) (4.16.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->trl[vllm]) (1.24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[vllm]) (3.29.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[vllm]) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[vllm]) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[vllm]) (2.2.2)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[vllm]) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[vllm]) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[vllm]) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[vllm]) (0.70.16)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[vllm]) (2025.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->trl[vllm]) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->trl[vllm]) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->trl[vllm]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->trl[vllm]) (2026.6.17)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl[vllm]) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl[vllm]) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl[vllm]) (0.26.8)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (6.2.6)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.2.2)
Requirement already satisfied: blake3 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.0.9)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (9.0.0)
Requirement already satisfied: protobuf!=6.30.*,!=6.31.*,!=6.32.*,!=6.33.0.*,!=6.33.1.*,!=6.33.2.*,!=6.33.3.*,!=6.33.4.*,>=5.29.6 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (5.29.6)
Requirement already satisfied: starlette>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.3.1)
Requirement already satisfied: openai>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (2.45.0)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.25.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (11.3.0)
Requirement already satisfied: prometheus-fastapi-instrumentator>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (8.1.0)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.13.0)
Requirement already satisfied: lm-format-enforcer==0.11.3 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.11.3)
Requirement already satisfied: llguidance<1.8.0,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.7.6)
Requirement already satisfied: outlines_core==0.2.14 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.2.14)
Requirement already satisfied: diskcache==5.6.3 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (5.6.3)
Requirement already satisfied: lark==1.2.2 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.2.2)
Requirement already satisfied: xgrammar<1.0.0,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.2.3)
Requirement already satisfied: partial-json-parser in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.2.1.1.post7)
Requirement already satisfied: jsonschema>=4.23.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (4.26.0)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (26.2.1)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.21.1)
Requirement already satisfied: mistral_common>=1.11.5 in /usr/local/lib/python3.12/dist-packages (from mistral_common[image]>=1.11.5->vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.11.7)
Requirement already satisfied: opencv-python-headless>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (5.0.0.93)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.17.0)
Requirement already satisfied: setuptools<81.0.0,>=77.0.3 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (80.10.2)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.8.2)
Requirement already satisfied: compressed-tensors==0.17.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.17.0)
Requirement already satisfied: depyf==0.20.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.20.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (3.1.2)
Requirement already satisfied: watchfiles in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.2.0)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (4.1.0)
Requirement already satisfied: ninja in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.13.0)
Requirement already satisfied: pybase64 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.4.3)
Requirement already satisfied: cbor2 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (6.1.3)
Requirement already satisfied: ijson in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (3.5.1)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.3.7)
Requirement already satisfied: openai-harmony>=0.0.3 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.0.8)
Requirement already satisfied: anthropic>=0.71.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.120.2)
Requirement already satisfied: model-hosting-container-standards<1.0.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.1.16)
Requirement already satisfied: mcp in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (2.0.0)
Requirement already satisfied: opentelemetry-sdk>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.44.0)
Requirement already satisfied: opentelemetry-api>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.44.0)
Requirement already satisfied: opentelemetry-exporter-otlp>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.44.0)
Requirement already satisfied: opentelemetry-semantic-conventions-ai>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.5.1)
Requirement already satisfied: numba==0.65.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.65.0)
Requirement already satisfied: torchaudio==2.11.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (2.11.0+cu128)
Requirement already satisfied: torchvision==0.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.26.0+cu128)
Requirement already satisfied: torchcodec>=0.14 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.15.0)
Requirement already satisfied: PyNvVideoCodec==2.0.4 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (2.0.4)
Requirement already satisfied: flashinfer-python==0.6.13 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.6.13)
Requirement already satisfied: flashinfer-cubin==0.6.13 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.6.13)
Requirement already satisfied: apache-tvm-ffi==0.1.9 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.1.9)
Requirement already satisfied: tilelang==0.1.9 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.1.9)
Requirement already satisfied: nvidia-cudnn-frontend>=1.19.1 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.26.0)
Requirement already satisfied: nvtx==0.2.15 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.2.15)
Requirement already satisfied: fastsafetensors>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.3.3)
Requirement already satisfied: nvidia-cutlass-dsl==4.5.2 in /usr/local/lib/python3.12/dist-packages (from nvidia-cutlass-dsl[cu13]==4.5.2->vllm<=0.25.1,>=0.17.0->trl[vllm]) (4.5.2)
Requirement already satisfied: quack-kernels>=0.3.3 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.5.0)
Requirement already satisfied: tokenspeed-mla==0.1.2 in /usr/local/lib/python3.12/dist-packages (from vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.1.2)
Requirement already satisfied: humming-kernels==0.1.10 in /usr/local/lib/python3.12/dist-packages (from humming-kernels[cu13]==0.1.10->vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.1.10)
Requirement already satisfied: loguru in /usr/local/lib/python3.12/dist-packages (from compressed-tensors==0.17.0->vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.7.3)
Requirement already satisfied: astor in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.13->vllm<=0.25.1,>=0.17.0->trl[vllm]) (8.4.2)
Requirement already satisfied: cuda-tile[tileiras] in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.13->vllm<=0.25.1,>=0.17.0->trl[vllm]) (1.3.0)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.13->vllm<=0.25.1,>=0.17.0->trl[vllm]) (13.610.43)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.13->vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.9.0)
Requirement already satisfied: triton in /usr/local/lib/python3.12/dist-packages (from humming-kernels==0.1.10->humming-kernels[cu13]==0.1.10->vllm<=0.25.1,>=0.17.0->trl[vllm]) (3.6.0)
Requirement already satisfied: pyelftools in /usr/local/lib/python3.12/dist-packages (from humming-kernels==0.1.10->humming-kernels[cu13]==0.1.10->vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.33)
Requirement already satisfied: cuda-bindings in /usr/local/lib/python3.12/dist-packages (from humming-kernels==0.1.10->humming-kernels[cu13]==0.1.10->vllm<=0.25.1,>=0.17.0->trl[vllm]) (12.9.7)
Requirement already satisfied: nvidia-cuda-runtime in /usr/local/lib/python3.12/dist-packages (from humming-kernels[cu13]==0.1.10->vllm<=0.25.1,>=0.17.0->trl[vllm]) (13.3.29)
Requirement already satisfied: nvidia-cuda-cccl in /usr/local/lib/python3.12/dist-packages (from humming-kernels[cu13]==0.1.10->vllm<=0.25.1,>=0.17.0->trl[vllm]) (13.3.3.4.1)
Requirement already satisfied: nvidia-cuda-nvcc in /usr/local/lib/python3.12/dist-packages (from humming-kernels[cu13]==0.1.10->vllm<=0.25.1,>=0.17.0->trl[vllm]) (13.2.86)
Requirement already satisfied: nvidia-cuda-nvrtc in /usr/local/lib/python3.12/dist-packages (from humming-kernels[cu13]==0.1.10->vllm<=0.25.1,>=0.17.0->trl[vllm]) (13.3.33)
Requirement already satisfied: interegular>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from lm-format-enforcer==0.11.3->vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.3.3)
Requirement already satisfied: llvmlite<0.48,>=0.47.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba==0.65.0->vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.47.0)
Requirement already satisfied: nvidia-cutlass-dsl-libs-base==4.5.2 in /usr/local/lib/python3.12/dist-packages (from nvidia-cutlass-dsl==4.5.2->nvidia-cutlass-dsl[cu13]==4.5.2->vllm<=0.25.1,>=0.17.0->trl[vllm]) (4.5.2)
Requirement already satisfied: nvidia-cutlass-dsl-libs-cu13==4.5.2 in /usr/local/lib/python3.12/dist-packages (from nvidia-cutlass-dsl[cu13]==4.5.2->vllm<=0.25.1,>=0.17.0->trl[vllm]) (4.5.2)
Requirement already satisfied: torch-c-dlpack-ext in /usr/local/lib/python3.12/dist-packages (from tilelang==0.1.9->vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.1.5)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from tilelang==0.1.9->vllm<=0.25.1,>=0.17.0->trl[vllm]) (0.5.4)
Requirement already satisfied: z3-solver<4.15.5,>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from tilelang==0.1.9->vllm<=0.25.1,>=0.17.0->trl[vllm]) (4.15.4.0)
Requirement already satisfied: tokenspeed-triton>=3.7.10.post20260505 in /usr/local/lib/python3.12/dist-packages (from tokenspeed-mla==0.1.2->vllm<=0.25.1,>=0.17.0->trl[vllm]) (3.8.10.post20260721)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[vllm]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[vllm]) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[vllm]) (12.8.1)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[vllm]) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[vllm]) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[vllm]) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[vllm]) (3.4.5)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[vllm]) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[vllm]) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[vllm]) (11.3.3.83)

In [ ]:
!pip install trl[GRPOTrainer]

Requirement already satisfied: trl[GRPOTrainer] in /usr/local/lib/python3.12/dist-packages (1.9.2)
WARNING: trl 1.9.2 does not provide the extra 'grpotrainer'
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl[GRPOTrainer]) (1.14.0)
Requirement already satisfied: datasets>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from trl[GRPOTrainer]) (5.0.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl[GRPOTrainer]) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl[GRPOTrainer]) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl[GRPOTrainer]) (5.13.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (1.23.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl[GRPOTrainer]) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (3.29.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl[GRPOTrainer]) (0.70.16)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (2025.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl[GRPOTrainer]) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl[GRPOTrainer]) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl[GRPOTrainer]) (0.26.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl[GRPOTrainer]) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl[GRPOTrainer]) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl[GRPOTrainer]) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl[GRPOTrainer]) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl[GRPOTrainer]) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl[GRPOTrainer]) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl[GRPOTrainer]) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl[GRPOTrainer]) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl[GRPOTrainer]) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl[GRPOTrainer]) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl[GRPOTrainer]) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (12.8.90)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl[GRPOTrainer]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl[GRPOTrainer]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl[GRPOTrainer]) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl[GRPOTrainer]) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl[GRPOTrainer]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl[GRPOTrainer]) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl[GRPOTrainer]) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl[GRPOTrainer]) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl[GRPOTrainer]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl[GRPOTrainer]) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl[GRPOTrainer]) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.56.2->trl[GRPOTrainer]) (0.1.2)

In [ ]:
from datasets import load_dataset
from trl import GRPOTrainer, GRPOConfig
import re

In [ ]:
from datasets import load_dataset
from trl import GRPOTrainer, GRPOConfig
from trl.rewards import accuracy_reward
import re

In [ ]:
print(train_dataset[0].keys())

dict_keys(['category', 'difficulty', 'quality', 'reward_model_score', 'conversation_tokens', 'prompt', 'completion'])

In [ ]:
import re
from datasets import load_dataset

# 1. Dataset Preparation
train_dataset = load_dataset("HuggingFaceTB/smoltalk", "smol-magpie-ultra", split="train[:200]")
eval_dataset = load_dataset("HuggingFaceTB/smoltalk", "smol-magpie-ultra", split="test[:200]")
model_name = "HuggingFaceTB/SmolLM2-135M"

def extract_prompt_completion_from_messages(item):
    prompt = None
    completion = None
    for message in item['messages']:
        if message['role'] == 'user':
            prompt = message['content']
        elif message['role'] == 'assistant':
            completion = message['content']
    return {'prompt': prompt, 'completion': completion}

prompt_to_gold_completion_map = {}
for item in train_dataset:
    extracted = extract_prompt_completion_from_messages(item)
    if extracted['prompt'] is not None and extracted['completion'] is not None:
        prompt_to_gold_completion_map[extracted['prompt']] = extracted['completion']

train_dataset = train_dataset.map(extract_prompt_completion_from_messages, remove_columns=['messages'])
eval_dataset = eval_dataset.map(extract_prompt_completion_from_messages, remove_columns=['messages'])

train_dataset = train_dataset.filter(lambda x: x['prompt'] is not None and x['completion'] is not None)
eval_dataset = eval_dataset.filter(lambda x: x['prompt'] is not None and x['completion'] is not None)


# 2. INSERTED: Format Reward Function
def reward_format(completions, **kwargs):
    """
    Rewards completions that contain a proper XML structure,
    such as <think>...</think> and <answer>...</answer> tags.
    """
    rewards = []
    # Pattern to check for matching open and close tags
    pattern = r"^<think>.*?</think>\s*<answer>.*?</answer>$"

    for completion in completions:
        # Clean up whitespace and check against the pattern
        clean_completion = completion.strip()
        if re.match(pattern, clean_completion, re.DOTALL):
            rewards.append(1.0)
        else:
            rewards.append(0.0)
    return rewards


# 3. Ground Truth Reward Function
def ground_truth_check_reward(prompts, completions, **kwargs):
    rewards = []
    reward_fn_kwargs = kwargs.get('reward_fn_kwargs', {})
    prompt_to_gold_completion_map = reward_fn_kwargs.get('prompt_to_gold_completion_map', {})

    for prompt, completion in zip(prompts, completions):
        gold_completion = prompt_to_gold_completion_map.get(prompt, None)
        if gold_completion and completion == gold_completion:
            rewards.append(1.0)
        else:
            rewards.append(0.0)
    return rewards


# 4. Combined Reward Function
def combined_reward_function(prompts, completions, **kwargs):
    format_rewards = reward_format(completions, **kwargs)
    truth_rewards = ground_truth_check_reward(prompts, completions, **kwargs)

    combined = [ (f_r + t_r) / 2.0 for f_r, t_r in zip(format_rewards, truth_rewards) ]
    return combined

In [ ]:
# training config
training_args = GRPOConfig(
    output_dir="output",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    logging_steps=10,
)

In [ ]:
# more detailed config (from the website)
training_args = GRPOConfig(
    output_dir="output",
    num_train_epochs=3,
    num_generations=4,  # Number of completions to generate for each prompt
    per_device_train_batch_size=4,  # We want to get all generations in one device batch
    # Optional but useful
    gradient_accumulation_steps=2,
    learning_rate=1e-5,
    logging_steps=10,
    # GRPO specific (optional)
    use_vllm=False  # Speed up generation, need to 'pip install trl[vllm]'. Disabled due to CUDA library error.
)

In [ ]:
# train_grpo.py
trainer = GRPOTrainer(
    model=model_name,
    args=training_args,
    reward_funcs=combined_reward_function,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset
    # reward_kwargs={'reward_args': {'prompt_to_gold_completion_map': prompt_to_gold_completion_map}}
)

Loading weights:   0%|          | 0/272 [00:00<?, ?it/s]

In [ ]:
trainer.train()

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 0}.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=300, training_loss=0.0, metrics={'train_runtime': 5025.6719, 'train_samples_per_second': 0.119, 'train_steps_per_second': 0.06, 'total_flos': 0.0, 'train_loss': 0.0, 'epoch': 3.0})

In [ ]:
trainer.evaluate()

{'eval_loss': 0.0,
 'eval_num_tokens': 0.0,
 'eval_completions/mean_length': 229.8925,
 'eval_completions/min_length': 119.24,
 'eval_completions/max_length': 256.0,
 'eval_completions/clipped_ratio': 0.815,
 'eval_completions/mean_terminated_length': 85.2466671514511,
 'eval_completions/min_terminated_length': 62.92,
 'eval_completions/max_terminated_length': 108.1,
 'eval_rewards/combined_reward_function/mean': 0.0,
 'eval_rewards/combined_reward_function/std': 0.0,
 'eval_reward': 0.0,
 'eval_reward_std': 0.0,
 'eval_frac_reward_zero_std': 1.0,
 'eval_entropy': 3.417125198841095,
 'eval_clip_ratio/low_mean': 0.0,
 'eval_clip_ratio/high_mean': 0.0,
 'eval_clip_ratio/region_mean': 0.0,
 'eval_clip_ratio/low_min': 0.0,
 'eval_clip_ratio/high_max': 0.0}